pipeline {
    // agent none
    agent {
        node {
            label 'AGENT'
        }
    }
    
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    
    stages {
        stage('init'){
            input {
                message "Should we connect?"
                ok "Yes, Thanks"
                
             }
            steps{
                echo "terraform init"
                sh """
                cd ec2
                terraform init  

                """              
            }

        }
        stage('Plan'){
            steps{
                echo "This is terraform plan"
                sh """
                cd ec2
                terraform plan

                """
            }
        }
        stage('apply'){
            steps{
                sh """
                echo 'This is terraform apply'
                cd ec2
                terraform apply -auto-approve

                """
            }
        }
        stage('Destroy'){
            input{
                    message "Should we continue for destroy"
                    Ok "Yes, Thanks"

                }
            steps{
                sh """
                 echo "This is destroy the instances"
                 cd ec2
                 terraform deploy
                """
            }
        }
    }

    post {
        always {
            echo 'it will always say hello again'
        }
        failure {
            echo " it will throw error message when build is failed"
        }
        success {
            echo "it will display when build when build is success"
        }
    }
}


//Errors
//MissingPropertyException: No such property: init for class 
//Sol: we have to install terraform and aws cli in AGENT server