pipeline {
    // agent none
    agent {
        node {
            label 'AGENT'
        }
    }
    
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    parameters {
        
        choice (name: 'action', choices: ['apply', 'destroy'], description: 'pick any one')
        booleanParam(name: 'skip_test', defaultValue: false, description: 'set to true to skip the test stage')
    }
    
    stages {
        stage('init'){
            input {
                message "Should we connect?"
                ok "Yes, Thanks"
                
             }
             when { expression { params.skip_test != true } }
                steps{
                echo "terraform init"
                sh """
                cd ec2
                terraform init  

                """              
            }
            

        }
        stage('Plan'){
            
            steps{
                echo "This is terraform plan"
                sh """
                cd ec2
                terraform plan

                """
            }
        }
        stage('apply'){
            when {
                expression { params.action == 'apply' }
            }
            steps{
                sh """
                echo 'This is terraform apply'
                cd ec2
                terraform apply -auto-approve

                """
            }
        }
        stage('Destroy'){
            when {
                expression { params.action == 'destroy' }
            }
            input {
                    message "Should we continue for destroy"
                    ok "Yes, Thanks"

                }
            steps{
                sh """
                 echo "This is destroy the instances"
                 cd ec2
                 terraform destroy -auto-approve
                """
            }
        }
    }

    post {
        always {
            echo 'it will always say hello again'
        }
        failure {
            echo " it will throw error message when build is failed"
        }
        success {
            echo "it will display when build when build is success"
        }
    }
}


//Errors
//MissingPropertyException: No such property: init for class 
//Solu: we have to install terraform and aws cli in AGENT server
// after it will run Jenkins file properly without failure.